"""add auth_codes table

Revision ID: 4ea1fbf2e4ed
Revises: 1542a50018c8
Create Date: 2026-01-19 11:02:53.186293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea1fbf2e4ed'
down_revision: Union[str, Sequence[str], None] = '1542a50018c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('email_verify', 'password_reset', name='authcodepurpose'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_codes_email'), 'auth_codes', ['email'], unique=False)
    op.create_index(op.f('ix_auth_codes_expires_at'), 'auth_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_codes_id'), 'auth_codes', ['id'], unique=False)
    op.create_index(op.f('ix_auth_codes_purpose'), 'auth_codes', ['purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_codes_purpose'), table_name='auth_codes')
    op.drop_index(op.f('ix_auth_codes_id'), table_name='auth_codes')
    op.drop_index(op.f('ix_auth_codes_expires_at'), table_name='auth_codes')
    op.drop_index(op.f('ix_auth_codes_email'), table_name='auth_codes')
    op.drop_table('auth_codes')
    # ### end Alembic commands ###
