"""add posters table

Revision ID: 6cba439996fa
Revises: 78af6118a3ad
Create Date: 2026-01-02 23:04:35.248778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cba439996fa'
down_revision: Union[str, Sequence[str], None] = '78af6118a3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cdn_key', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posters_id'), 'posters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posters_id'), table_name='posters')
    op.drop_table('posters')
    # ### end Alembic commands ###
