"""add category seo and slug

Revision ID: 70fa118faa0f
Revises: d9dd59772500
Create Date: 2026-01-06 10:55:57.698690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70fa118faa0f'
down_revision: Union[str, Sequence[str], None] = 'd9dd59772500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=120), nullable=False))
    op.add_column('categories', sa.Column('seo_title', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('seo_description', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('seo_h1', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('seo_intro', sa.String(), nullable=True))
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'seo_intro')
    op.drop_column('categories', 'seo_h1')
    op.drop_column('categories', 'seo_description')
    op.drop_column('categories', 'seo_title')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
