"""add poster click_count

Revision ID: d9dd59772500
Revises: 6cba439996fa
Create Date: 2026-01-04 09:17:56.951390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9dd59772500'
down_revision: Union[str, Sequence[str], None] = '6cba439996fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posters', sa.Column('click_count', sa.Integer(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posters', 'click_count')
    # ### end Alembic commands ###
