"""lisitng table

Revision ID: fa8aeeb8adc7
Revises: 780032317240
Create Date: 2025-11-13 10:23:45.098458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8aeeb8adc7'
down_revision: Union[str, Sequence[str], None] = '780032317240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending_admin', 'awaiting_payment', 'active', 'expired', 'rejected', 'draft', name='listingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('visibility_until', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('whatsapp', sa.String(length=100), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('tiktok', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('youtube', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('admin_comment', sa.String(length=500), nullable=True),
    sa.Column('sponsored_from', sa.DateTime(), nullable=True),
    sa.Column('sponsored_until', sa.DateTime(), nullable=True),
    sa.Column('click_counter', sa.Integer(), nullable=True),
    sa.Column('click_counter_sponsored', sa.Integer(), nullable=True),
    sa.Column('click_website', sa.Integer(), nullable=True),
    sa.Column('click_email', sa.Integer(), nullable=True),
    sa.Column('click_phone', sa.Integer(), nullable=True),
    sa.Column('click_whatsapp', sa.Integer(), nullable=True),
    sa.Column('click_instagram', sa.Integer(), nullable=True),
    sa.Column('click_tiktok', sa.Integer(), nullable=True),
    sa.Column('click_facebook', sa.Integer(), nullable=True),
    sa.Column('click_youtube', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
